-- SQL Script to Restore Yamaha NMAX to Database
-- You can run this from Supabase SQL Editor or your admin panel

-- Insert Yamaha NMAX bike
INSERT INTO public.bikes (
  id,
  name,
  model,
  engine,
  transmission,
  fuel_capacity,
  daily_price,
  weekly_price,
  monthly_price,
  status,
  image,
  year,
  features,
  description,
  description_en,
  description_ru,
  description_id,
  description_de,
  description_uz,
  description_ar,
  features_en,
  features_ru,
  features_id,
  features_de,
  features_uz,
  features_ar
) VALUES (
  'yamaha-nmax',
  'Yamaha NMAX',
  '155cc',
  '155cc',
  'CVT',
  '7.1L',
  10,
  55,
  180,
  'available',
  'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800',
  2024,
  ARRAY['Helmet included', '24/7 support', 'Sporty design', 'Powerful engine', 'ABS braking'],
  'Modern performance scooter combining style with capability. Aggressive design and powerful performance for confident riding.',
  'Modern performance scooter combining style with capability. Aggressive design and powerful performance for confident riding. Advanced features and smooth handling inspire adventure. Perfect balance between sport and comfort.',
  'Современный скутер производительности, сочетающий стиль с возможностями. Агрессивный дизайн и мощная производительность для уверенной езды. Продвинутые функции и плавное управление вдохновляют на приключения.',
  'Skuter performa modern yang menggabungkan gaya dengan kemampuan. Desain agresif dan performa kuat untuk berkendara yang percaya diri. Fitur canggih dan handling halus menginspirasi petualangan.',
  'Moderner Leistungsroller, der Stil mit Fähigkeiten verbindet. Aggressives Design und starke Leistung für sicheres Fahren. Fortgeschrittene Funktionen und sanfte Handhabung inspirieren zu Abenteuern.',
  'Stil bilan imkoniyatni birlashtiradigan zamonaviy unumdorlik skuteri. Ishonchli haydash uchun agressiv dizayn va kuchli unumdorlik. Ilg''or xususiyatlar va silliq boshqaruv sarguzashtlarga ilhom beradi.',
  'سكوتر أداء حديث يجمع بين الأناقة والقدرة. تصميم عدواني وأداء قوي للقيادة الواثقة. ميزات متقدمة ومعالجة سلسة تلهم المغامرة. توازن مثالي بين الرياضة والراحة.',
  ARRAY['Helmet included', '24/7 support', 'Sporty design', 'Powerful engine', 'ABS braking'],
  ARRAY['Шлем включен', 'Поддержка 24/7', 'Спортивный дизайн', 'Мощный двигатель', 'Торможение ABS'],
  ARRAY['Helm termasuk', 'Dukungan 24/7', 'Desain sporty', 'Mesin bertenaga', 'Pengereman ABS'],
  ARRAY['Helm inklusive', 'Support 24/7', 'Sportliches Design', 'Starker Motor', 'ABS-Bremsen'],
  ARRAY['Dubulga kiritilgan', '24/7 yordam', 'Sport dizayn', 'Kuchli dvigatel', 'ABS tormozlash'],
  ARRAY['خوذة مشمولة', 'دعم 24/7', 'تصميم رياضي', 'محرك قوي', 'فرامل ABS']
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  model = EXCLUDED.model,
  engine = EXCLUDED.engine,
  transmission = EXCLUDED.transmission,
  fuel_capacity = EXCLUDED.fuel_capacity,
  daily_price = EXCLUDED.daily_price,
  weekly_price = EXCLUDED.weekly_price,
  monthly_price = EXCLUDED.monthly_price,
  status = EXCLUDED.status,
  image = EXCLUDED.image,
  year = EXCLUDED.year,
  features = EXCLUDED.features,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en,
  description_ru = EXCLUDED.description_ru,
  description_id = EXCLUDED.description_id,
  description_de = EXCLUDED.description_de,
  description_uz = EXCLUDED.description_uz,
  description_ar = EXCLUDED.description_ar,
  features_en = EXCLUDED.features_en,
  features_ru = EXCLUDED.features_ru,
  features_id = EXCLUDED.features_id,
  features_de = EXCLUDED.features_de,
  features_uz = EXCLUDED.features_uz,
  features_ar = EXCLUDED.features_ar;

-- Verify the insert
SELECT id, name, model, daily_price, status FROM public.bikes WHERE id = 'yamaha-nmax';
