-- Update Honda Beat with translations
UPDATE public.bikes SET
  description_en = 'Perfect for exploring Lombok''s coastal villages and narrow island roads. Ideal for solo travelers and budget-conscious adventurers. Excellent fuel efficiency (55+ km/liter) makes it perfect for long island explorations. Features comfortable seat, reliable engine, and easy maneuverability through crowded markets. Great for short daily trips and island hopping.',
  description_ru = 'Идеален для исследования прибрежных деревень Ломбока и узких дорог острова. Идеально подходит для одиночных путешественников и экономных туристов. Отличная топливная экономичность (более 55 км/л) делает его идеальным для длительных исследований острова. Удобное сиденье, надежный двигатель и простое управление в загруженных местах. Отлично подходит для коротких поездок по городу и прыжков между островами.',
  description_id = 'Sempurna untuk menjelajahi desa-desa pantai Lombok dan jalan-jalan sempit pulau. Ideal untuk pemilih solo dan petualang yang cerdas biaya. Efisiensi bahan bakar yang luar biasa (lebih dari 55 km/liter) membuatnya sempurna untuk eksplorasi pulau jangka panjang. Fitur kursi yang nyaman, mesin yang andal, dan kemudahan maneuver melalui pasar yang ramai. Bagus untuk perjalanan singkat kota dan island hopping.',
  description_de = 'Perfekt zum Erkunden von Atolls und engen Inselstraßen. Ideal für Einzelreisende und sparsame Abenteurer. Hervorragende Kraftstoffeffizienz (über 55 km/Liter) macht es perfekt für längere Inselexplorationspläne. Verfügt über bequemen Sitz, zuverlässigen Motor und einfache Manövrierbarkeit durch überfüllte Märkte. Großartig für kurze Stadtfahrten und Inselhopping.',
  description_uz = 'Lombok''s uy qishloqlari va tor orol yo''lllarini o''rganish uchun mukammal. Yakkachaga yo''lovchilar va buxgalter sarguzashtlarni yoqtiradiganlarga ideal. Ajoyib yoqilg''i tejamkorligi (55+ km/litr) uni uzoq orol tadqiqotlar uchun ideal qiladi. Qulaylik bilan o''tirish o''rni, ishonchli dvigatel va shaxarning ko''p qidirilgan joylaridagi oson manevrXR. Qisqa shahar sayohatlar va orol tulash uchun ajoyib.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'Fuel Efficient', 'Perfect for City', 'Easy Parking'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'Экономичный расход', 'Идеален для города', 'Простая парковка'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Hemat Bahan Bakar', 'Sempurna untuk Kota', 'Parkir Mudah'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'Kraftstoffsparend', 'Perfekt für Stadt', 'Einfaches Parken'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'Yoqilg''i Tejamkorligi', 'Shahar uchun mukammal', 'Oson parkovka']
WHERE name = 'Honda Beat';

-- Update Honda Street with translations
UPDATE public.bikes SET
  description_en = 'Stylish and comfortable scooter perfect for city exploration and short beach trips. Beautiful design turns heads while offering practical features for daily use. Smooth automatic transmission makes it ideal for first-time riders. Spacious storage for beach essentials and day trips. Reliable Honda engineering with excellent handling on both smooth and rough roads.',
  description_ru = 'Стильный и удобный скутер идеален для исследования города и коротких пляжных поездок. Красивый дизайн привлекает внимание при практичных функциях для ежедневного использования. Плавная автоматическая трансмиссия идеальна для новых водителей. Просторное хранилище для пляжных вещей и дневных поездок. Надежная инженерия Honda с отличной управляемостью на гладких и ухабистых дорогах.',
  description_id = 'Skuter bergaya dan nyaman sempurna untuk eksplorasi kota dan perjalanan pantai singkat. Desain indah menarik perhatian sambil menawarkan fitur praktis untuk penggunaan sehari-hari. Transmisi otomatis yang mulus ideal untuk pengendara pemula. Penyimpanan luas untuk barang-barang pantai dan perjalanan sehari. Rekayasa Honda yang andal dengan penanganan yang sangat baik di jalan halus dan kasar.',
  description_de = 'Stilvoller und komfortabler Roller, perfekt für die Stadterkundung und kurze Strandausflüge. Schönes Design fällt auf und bietet praktische Funktionen für den täglichen Gebrauch. Sanfte Automatikschaltung ideal für Anfänger. Großzügiger Stauraum für Strandutensilien und Tagesausflüge. Zuverlässige Honda-Ingenieurkunst mit hervorragendem Handling auf glatten und holprigen Straßen.',
  description_uz = 'Sharoitli va qulay skuter shahar tadqiqoti va qisqa plyaj sayohatlar uchun mukammal. Chiroyli dizayn e''tiborni tortadi va kundalik foydalanish uchun amaliy xususiyatlari mavjud. Silliq avtomatik transmissiya yangi chavandozlar uchun ideal. Plyaj moddasi va kunlik sayohatlar uchun keng xozja joy. Ishonchli Honda muhandisligi silliq va buziladigan yo''llarda ajoyib boshqaruv.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'Comfortable Seat', 'Stylish Design', 'Good Storage'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'Удобное сиденье', 'Стильный дизайн', 'Хорошее хранилище'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Kursi Nyaman', 'Desain Bergaya', 'Penyimpanan Bagus'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'Bequemer Sitz', 'Stilvolles Design', 'Guter Stauraum'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'Qulaylik bilan o''tirish', 'Sharoitli dizayn', 'Yaxshi xozja joy']
WHERE name = 'Honda Street';

-- Update Honda Vario 125 with translations
UPDATE public.bikes SET
  description_en = 'The versatile all-rounder for island adventures. Powerful enough for uphill climbs to waterfalls and temples, yet economical for city riding. Advanced fuel injection ensures smooth acceleration on winding mountain roads. Large storage compartment perfect for beach gear and souvenirs. Comfortable ride for both short city trips and full-day island explorations. USB charger keeps your adventure camera powered.',
  description_ru = 'Универсальный универсал для островных приключений. Достаточно мощный для подъема к водопадам и храмам, но экономичный для городской езды. Продвинутая топливная система обеспечивает плавное ускорение на извилистых горных дорогах. Большой отсек для хранения идеален для пляжного снаряжения и сувениров. Удобная езда для коротких городских поездок и целодневных исследований острова. USB-зарядка держит вашу экшн-камеру заряженной.',
  description_id = 'Semua-rounder serbaguna untuk petualangan pulau. Cukup kuat untuk mendaki ke air terjun dan kuil, namun ekonomis untuk berkendara di kota. Injeksi bahan bakar canggih memastikan akselerasi halus di jalan gunung yang berliku. Kompartemen penyimpanan besar sempurna untuk perlengkapan pantai dan suvenir. Perjalanan yang nyaman untuk perjalanan kota singkat dan eksplorasi pulau sepanjang hari. Pengisi daya USB membuat kamera aksi Anda tetap bertenaga.',
  description_de = 'Der vielseitige Allrounder für Inselabenteuer. Kraftvoll genug für Uphill-Klettertouren zu Wasserfällen und Tempeln, aber wirtschaftlich für das Stadtfahren. Fortschrittliche Einspritzung sorgt für sanfte Beschleunigung auf kurvigen Bergstraßen. Großes Staufach perfekt für Strandausrüstung und Souvenirs. Komfortable Fahrt sowohl für kurze Stadtausflüge als auch für ganztägige Inselexplorationspläne. USB-Ladeanschluss hält Ihre Action-Kamera mit Strom versorgt.',
  description_uz = 'Orol sarguzashtlari uchun o''zgaruvchan har qanday yordamchi. Shualliklarga va ibadetxonalarga ko''tarilish uchun etarli kuchli, lekin shahar sur''ati uchun tejamkorl. Ilg''or yoqilg''i in''ektsiyasi buziladigan tog'' yo''llarida silliq tezlashtirish ta''minlaydi. Plyaj uskunasi va suvenirlari uchun katta xozja bo''limi mukammal. Qisqa shahar sayohatlar va butun kun orol tadqiqotlar uchun qulay sayohat. USB zaryadlovchi sizning sarguzasht kamerangizni quvvatini ta''minlaydi.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'USB Charger', 'Large Storage', 'Fuel Efficient', 'Great for Tours'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'USB-зарядка', 'Большое хранилище', 'Экономичный расход', 'Отлично для туров'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Pengisi Daya USB', 'Penyimpanan Besar', 'Hemat Bahan Bakar', 'Bagus untuk Tur'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'USB-Ladeanschluss', 'Großer Stauraum', 'Kraftstoffsparend', 'Großartig für Touren'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'USB zaryadlovchi', 'Katta xozja joy', 'Yoqilg''i tejamkorligi', 'Turlar uchun ajoyib']
WHERE name = 'Honda Vario 125';

-- Update Honda Vario 160 with translations
UPDATE public.bikes SET
  description_en = 'Premium power and luxury comfort for serious adventurers. Advanced braking system and modern ABS technology ensure safety on demanding terrain. Powerful 160cc engine tackles steep mountain roads with ease. Premium comfort seat designed for all-day riding. Digital dashboard with smart features. Perfect for full-day tours, multi-island adventures, and experienced riders seeking top performance.',
  description_ru = 'Премиальная мощность и роскошный комфорт для серьезных искателей приключений. Продвинутая система торможения и современная технология ABS обеспечивают безопасность на сложной местности. Мощный двигатель 160 куб. см легко справляется с крутыми горными дорогами. Премиальное удобное сиденье, разработанное для целодневной езды. Цифровая приборная панель с умными функциями. Идеален для целодневных туров, многоостровных приключений и опытных водителей, ищущих максимальную производительность.',
  description_id = 'Kekuatan premium dan kenyamanan mewah untuk para petualang serius. Sistem pengereman canggih dan teknologi ABS modern memastikan keselamatan di medan yang menantang. Mesin 160cc yang kuat mengatasi jalan gunung yang curam dengan mudah. Kursi kenyamanan premium yang dirancang untuk berkendara sepanjang hari. Dasbor digital dengan fitur pintar. Sempurna untuk tur sehari penuh, petualangan multi-pulau, dan pengendara berpengalaman yang mencari performa teratas.',
  description_de = 'Premium-Leistung und Luxuskomfort für ernsthafte Abenteurer. Fortgeschrittenes Bremssystem und moderne ABS-Technologie gewährleisten Sicherheit auf anspruchsvollem Gelände. Der leistungsstarke 160er-Motor bewältigt steile Bergstraßen mit Leichtigkeit. Premium-Komfortsitz für ganztägiges Fahren entwickelt. Digitales Dashboard mit intelligenten Funktionen. Perfekt für ganztägige Touren, Mehrinsel-Abenteuer und erfahrene Fahrer, die maximale Leistung suchen.',
  description_uz = 'Premium kuch va hashamatli qulaylik jiddiy sarguzashtlovchilar uchun. Ilg''or k''o''z uskunasi va zamonaviy ABS texnologiyasi murakkab arzida xavfsizlik ta''minlaydi. Kuchli 160 sm3 dvigatel to''lqin tog'' yo''llarini osonlik bilan engib o''tadi. Butun kun chavandozlik uchun mo''ljallangan premium qulaylik o''rni. Aqlli xususiyatlari bilan raqamli boshqaruv panloni. Butun kun turlar, ko''p orol sarguzashtlari va maksimal unumdorlikni izlayotgan tajribali chavandozlar uchun mukammal.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'USB Charger', 'Integrated ABS', 'Digital Dashboard', 'Premium Seat', 'Advanced Braking'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'USB-зарядка', 'Интегрированный ABS', 'Цифровая приборная панель', 'Премиальное сиденье', 'Продвинутое торможение'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Pengisi Daya USB', 'ABS Terintegrasi', 'Dasbor Digital', 'Kursi Premium', 'Pengereman Canggih'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'USB-Ladeanschluss', 'Integriertes ABS', 'Digitales Dashboard', 'Premium-Sitz', 'Fortgeschrittenes Bremsen'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'USB zaryadlovchi', 'Integrallashgan ABS', 'Raqamli boshqaruv paneli', 'Premium o''rni', 'Ilg''or k''o''z']
WHERE name = 'Honda Vario 160';

-- Update Yamaha NMAX with translations
UPDATE public.bikes SET
  description_en = 'Modern performance scooter combining style with capability. Aggressive design and powerful performance for confident riding. Advanced features and smooth handling inspire adventure. Perfect balance between sport and comfort. Great for riders who want style without compromising on power and reliability.',
  description_ru = 'Современный скутер производительности, сочетающий стиль с возможностями. Агрессивный дизайн и мощная производительность для уверенной езды. Продвинутые функции и плавное управление вдохновляют на приключения. Идеальный баланс между спортом и комфортом. Отлично для водителей, которые хотят стиль без ущерба для мощности и надежности.',
  description_id = 'Skuter performa modern yang menggabungkan gaya dengan kemampuan. Desain agresif dan performa kuat untuk berkendara yang percaya diri. Fitur canggih dan handling halus menginspirasi petualangan. Keseimbangan sempurna antara olahraga dan kenyamanan. Hebat untuk pengendara yang menginginkan gaya tanpa mengorbankan kekuatan dan keandalan.',
  description_de = 'Moderner Leistungsroller, der Stil mit Fähigkeiten verbindet. Aggressives Design und starke Leistung für sicheres Fahren. Fortgeschrittene Funktionen und sanfte Handhabung inspirieren zu Abenteuern. Perfekte Balance zwischen Sport und Komfort. Großartig für Fahrer, die Stil ohne Kompromisse bei Kraft und Zuverlässigkeit wollen.',
  description_uz = 'Stil bilan salohiyatni birlashtiradigan zamonaviy unumdorlik skuteri. Ishonchli chavandozlik uchun agressiv dizayn va kuchli unumdorlik. Ilg''or xususiyatlar va silliq boshqaruv sarguzashtlarga ilhom beradi. Sport va qulaylik orasida mukammal balans. Stil istaydigan lekin kuch va ishonchga qurbon bo''lmagan chavandozlar uchun ajoyib.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'Modern Design', 'Powerful Engine', 'Smooth Handling'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'Современный дизайн', 'Мощный двигатель', 'Плавное управление'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Desain Modern', 'Mesin Bertenaga', 'Handling Halus'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'Modernes Design', 'Starker Motor', 'Sanfte Bedienung'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'Zamonaviy dizayn', 'Kuchli dvigatel', 'Silliq boshqaruv']
WHERE name = 'Yamaha NMAX';

-- Update Yamaha Aerox with translations
UPDATE public.bikes SET
  description_en = 'Sportiest performer in the fleet for thrill-seeking adventurers. Sleek aerodynamic design turns heads everywhere. Powerful 155cc engine delivers impressive acceleration. Premium LED lights and luxury design appeal. Advanced features and responsive handling make it ideal for experienced riders. Perfect for full-day adventures and multi-island exploration.',
  description_ru = 'Самый спортивный исполнитель в парке для любителей острых ощущений. Обтекаемый аэродинамический дизайн привлекает взгляды везде. Мощный двигатель объемом 155 куб. см обеспечивает впечатляющее ускорение. Премиальные светодиодные фары и роскошный дизайн привлекают внимание. Продвинутые функции и быстрое управление идеальны для опытных водителей. Идеален для целодневных приключений и многоостровного исследования.',
  description_id = 'Pemain teratas yang paling olahraga dalam armada untuk petualang yang mencari sensasi. Desain aerodinamis yang ramping menarik perhatian di mana-mana. Mesin 155cc yang kuat memberikan akselerasi yang mengesankan. Lampu LED premium dan daya tarik desain mewah. Fitur canggih dan handling responsif ideal untuk pengendara berpengalaman. Sempurna untuk petualangan sepanjang hari dan eksplorasi multi-pulau.',
  description_de = 'Der sportlichste Performer in der Flotte für abenteuerlustige Abenteurer. Schlankes aerodynamisches Design fällt überall auf. Der leistungsstarke 155-ccm-Motor bietet beeindruckende Beschleunigung. Premium-LED-Leuchten und Luxusdesign-Appeal. Fortgeschrittene Funktionen und ansprechendes Handling machen es ideal für erfahrene Fahrer. Perfekt für ganztägige Abenteuer und Mehrinsel-Exploration.',
  description_uz = 'Povernidan izlayotganlar uchun flotaning eng sportiv ijrochisi. Engil aerodinamik dizayn hamma joyda e''tiborni tortadi. Kuchli 155 sm3 dvigatel hayajonli tezlashtirish beradi. Premium LED chiroqlar va hashamatli dizayn jozibasi. Ilg''or xususiyatlar va tez javob beradigan boshqaruv tajribali chavandozlar uchun ideal. Butun kun sarguzashtlar va ko''p orol tadqiqotlari uchun mukammal.',
  features_en = ARRAY['Free Helmet', 'Lock Included', 'Premium LED Lights', 'Luxury Design', 'Powerful Engine', '5.5L Fuel Tank', 'Advanced Braking'],
  features_ru = ARRAY['Бесплатный шлем', 'Замок включен', 'Премиальные светодиодные фары', 'Роскошный дизайн', 'Мощный двигатель', 'Топливный бак 5,5 л', 'Продвинутое торможение'],
  features_id = ARRAY['Helm Gratis', 'Kunci Disertakan', 'Lampu LED Premium', 'Desain Mewah', 'Mesin Bertenaga', 'Tangki Bahan Bakar 5.5L', 'Pengereman Canggih'],
  features_de = ARRAY['Helm kostenlos', 'Schloss inbegriffen', 'Premium-LED-Leuchten', 'Luxusdesign', 'Starker Motor', '5,5L Benzintank', 'Fortgeschrittenes Bremsen'],
  features_uz = ARRAY['Bepul shlem', 'Kalitning kiritilishi', 'Premium LED chiroqlari', 'Hashamatli dizayn', 'Kuchli dvigatel', '5,5L yoqilg''i bakasi', 'Ilg''or k''o''z']
WHERE name = 'Yamaha Aerox';
